declare module "un-ods-cards" {
  export const OdsCard1: React.FC<React.SVGProps<SVGSVGElement>>;
  export const OdsCard2: React.FC<React.SVGProps<SVGSVGElement>>;
  export const OdsCard3: React.FC<React.SVGProps<SVGSVGElement>>;
  export const OdsCard4: React.FC<React.SVGProps<SVGSVGElement>>;
  export const OdsCard5: React.FC<React.SVGProps<SVGSVGElement>>;
  export const OdsCard6: React.FC<React.SVGProps<SVGSVGElement>>;
  export const OdsCard7: React.FC<React.SVGProps<SVGSVGElement>>;
  export const OdsCard8: React.FC<React.SVGProps<SVGSVGElement>>;
  export const OdsCard9: React.FC<React.SVGProps<SVGSVGElement>>;
  export const OdsCard10: React.FC<React.SVGProps<SVGSVGElement>>;
  export const OdsCard11: React.FC<React.SVGProps<SVGSVGElement>>;
  export const OdsCard12: React.FC<React.SVGProps<SVGSVGElement>>;
  export const OdsCard13: React.FC<React.SVGProps<SVGSVGElement>>;
  export const OdsCard14: React.FC<React.SVGProps<SVGSVGElement>>;
  export const OdsCard15: React.FC<React.SVGProps<SVGSVGElement>>;
  export const OdsCard16: React.FC<React.SVGProps<SVGSVGElement>>;
  export const OdsCard17: React.FC<React.SVGProps<SVGSVGElement>>;
}
